#include <stdio.h>
#include <stdlib.h>

int main(int argc, char **argv)
{
    FILE *in, *out;
    int c, n = 0;

    if (argc != 4) {
        fprintf(stderr, "usage: bin2c <input> <output.c> <symbol>\n");
        return 2;
    }
    in = fopen(argv[1], "rb");
    if (!in) { perror(argv[1]); return 1; }
    out = fopen(argv[2], "wb");
    if (!out) { perror(argv[2]); fclose(in); return 1; }

    fprintf(out, "/* generated by tools/bin2c from %s - do not edit */\n", argv[1]);
    fprintf(out, "const unsigned char %s[] = {\n", argv[3]);
    while ((c = fgetc(in)) != EOF) {
        fprintf(out, "0x%02x,", c);
        if (++n % 20 == 0) fputc('\n', out);
    }
    fprintf(out, "0x00};\n");
    fprintf(out, "const unsigned int %s_len = %d;\n", argv[3], n);
    fclose(in);
    fclose(out);
    return 0;
}
